#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# remove mailx lock dir
rm -rf /var/mail/\:saved/

echo "* Allow dovecot user access to redis"
usermod -G redis dovecot

echo "* Install dovecot auth daemon"
npm install -g dovecot-core-authd
svccfg import /opt/local/lib/node_modules/dovecot-core-authd/manifest.xml

echo "* Install spiped"
pkg_add http://pkgsrc.smartos.skylime.net/skylime-extra/2014Q1/x86_64/spiped-1.3.1nb3.tgz

echo "* Create ssl folder"
mkdir -p /opt/local/etc/dovecot/ssl

echo "* Enable mdata-setup script"
svccfg import /tmp/mdata-setup.xml
rm /tmp/mdata-setup.xml

# munin
echo "* Create munin template file that will be used during mdata setup"
cp /opt/local/etc/munin/munin-node.conf /opt/local/etc/munin/munin-node.conf.tpl

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
